public class Candidates {
    public string Name;
    public string Gender;
    public static string CompanyName;

    
    public void printCandidates() {
        system.debug('Candidate Name is ' + Name + '(' +Gender +')');
        system.debug('Candidate Name is ' + CompanyName);

        public static void printCandidateInfoSt() {
            System.debug('company name is ' + CompanyName);
            System.debug('name = ' + Name); 
        }
    }
}
