public  class ListDemo {
    public static string candidatesList(integer indx) {

        public static void randomIntegerList() {

            public static void allCats(integer indx) {
                cat falconsCat = new cat('fluffykins', 'white');
                cat vitapCat = new cat('Simba', 'brown');

                

                List<cat> cats = new list<cat>();
                cats.add(falconsCat);
                cats.add(vitapCat);
                System.debug('all cats are ' + cats);


                public static void allCats(integer indx) {
                car lm = new car();
        // list<string> listCandidates = new List<string>();
        // listCandidates.add('Marc');    
        // listCandidates.add('Elon');
        // listCandidates.add('Bill');
        // listCandidates.add('Marc');
        // System.debug('candidates are ' + listCandidates);
        // string returnString = '';
      
        
        // if (indx < listCandidates.size()){
        //     returnString = listCandidates[indx];
        //             } else {
        //                 returnString = 'No such value found';
        //             }
        //             return returnString;

        //  }
        //     public static void randomIntegerList(){
        //     list<integer> listInteger = new List<integer>();
        // listInteger.add(10);
        // listInteger.add(15);
        // listInteger.add(21);
        // listInteger.add(15);
        // listInteger.add(15);
        // System.debug('list of random integer ' + listInteger);
            

    }
}
